export const appraisalData = `
Data Elements
PROPERTY ADDRESS STATE
PROPERTY ADDRESS CITY
PROPERTY ADDRESS LINE 1
PROPERTY ADDRESS LINE 2
PROPERTY ADDRESS COUNTY
PROPERTY ADDRESS ZIPCODE
EFFECTIVE DATE OF APPRAISAL
TOTAL NUMBER OF UNITS SOLD
TOTAL NUMBER OF UNITS
APPRAISAL AMOUNT
NUMBER OF BEDROOMS
YEAR BUILT
ATTACHMENT TYPE
OWNERSHIP INTEREST
SUPERVISORY APPRAISER STATE LICENSE # OR STATE CERTIFICATION #
APPRAISER LICENCE TYPE
APPRAISER STATE LICENSE #
APPRAISER STATE CERTIFICATION #
APPRAISER COMPANY NAME
APPRAISER FULL NAME
PROJECT NAME
PROPERTY VALUATION CONDITIONAL CONCLUSION
LIVING UNIT COUNT
PROPERTY ACREAGE NUMBER
PUD INDICATOR
PROPERTY VALUATION FORM TYPE
DOCUMENT FORM ISSUING ENTITY NUMBER IDENTIFIER
PROPERTY VALUATION METHOD TYPE
NUMBER OF BATHROOMS
TOTAL ROOM TYPE SUMMARY COUNT
CONSTRUCTION METHOD TYPE
PROPERTY VALUATION EFFECTIVE DATE
OVERALL CONDITION RATING IDENTIFIER
OVERALL QUALITY RATING IDENTIFIER
BORROWER LAST NAME
BORROWER FIRST NAME
BORROWER FULL NAME
BORROWER SUFFIX NAME
BORROWER MIDDLE NAME
`;
