export const creditData = `
Data Elements
CREDIT CARD ACCOUNT NUMBER
CREDIT REQUEST DATE/TIME
CREDIT BUREAU NAME
BORROWER SUFFIX NAME
BORROWER MIDDLE NAME
BORROWER FIRST NAME
BORROWER LAST NAME
BORROWER FULL NAME
BORROWER EQUIFAX SCORE
BORROWER EXPERIAN SCORE
BORROWER TRANSUNION SCORE
BORROWER TAX PAYER IDENTIFIER TYPE VALUE
BORROWER TAX PAYER IDENTIFIER TYPE
`;
