export const paystubData = `
Data Elements
PERIOD START DATE
PERIOD END DATE
PAY DATE
EMPLOYER NAME
EMPLOYER ADDRESS LINE 1
EMPLOYER CITY
EMPLOYER STATE
EMPLOYER ZIPCODE
FIRST NAME
LAST NAME
SOCIAL SECURITY NUMBER
EMPLOYEE ADDRESS LINE 1
EMPLOYEE CITY
EMPLOYEE STATE
EMPLOYEE ZIPCODE
BASE/REGULAR RATE
YTD BASE/REGULAR PAY
CURRENT BASE/REGULAR PAY
NET PAYMENT
BASE/REGULAR HOURS
BASE/REGULAR HOURS YTD
CURRENT GROSS PAY
YTD GROSS PAY
OVERTIME HOURS
YTD OVERTIME PAY
CURRENT BONUS PAY
YTD BONUS PAY
CURRENT VACATION PAY
YTD VACATION PAY
`;
