export const w2Data = `
Data Elements
SOCIAL SECURITY NUMBER
FORM YEAR
EMPLOYER NAME
EMPLOYER ADDRESS LINE 1
EMPLOYER CITY
EMPLOYER STATE
EMPLOYER ZIPCODE
EMPLOYER IDENTIFICATION NUMBER (EIN)
FIRST NAME
LAST NAME
EMPLOYEE ADDRESS LINE 1
EMPLOYEE CITY
EMPLOYEE STATE
EMPLOYEE ZIPCODE
MEDICARE WAGES AND TIPS
WAGES, TIPS, OTHER COMPENSATION
SOCIAL SECURITY WAGES
SOCIAL SECURITY TAX WITHHELD
SOCIAL SECURITY TIPS
MEDICARE TAX WITHHELD
FEDERAL INCOME TAX WITHHELD
ALLOCATED TIPS
DEPENDENT CARE BENEFITS
LOCAL WAGES AND TIPS
FORM STATE
EMPLOYER STATE ID NUMBER
STATE WAGES AND TIPS
`;
