export const disclosureData = `
Data Elements
DISBURSEMENT DATE
PREPAYMENT PENALTY INDICATOR
INITIAL PRINCIPAL AND INTEREST PAYMENT AMOUNT
INTEREST RATE
LOAN AMOUNT
CLOSING DATE
LOAN AMORTIZATION PERIOD TYPE
LOAN AMORTIZATION PERIOD COUNT
DATE ISSUED
PURCHASE PRICE AMOUNT
INTEREST ONLY INDICATOR
LENDER FULL NAME
PROJECTED PAYMENT MI PAYMENT AMOUNT
MI INITIAL PREMIUM AMOUNT
MORTGAGE TYPE
LOAN PURPOSE TYPE
PROPOSED TOTAL MONTHLY HOUSING EXPENSE
CASH TO BORROWER AT CLOSING AMOUNT
CASH FROM BORROWER AT CLOSING AMOUNT
PROPERTY TAXES PROJECTED PAYMENT ESCROWED TYPE
HOMEOWNERS INSURANCE PROJECTED PAYMENT ESCROWED TYPE
PROJECTED PAYMENT ESTIMATED TAXES INSURANCE ASSESSMENT COMPONENT TYPE
BORROWER SIGNATURE PRESENT INDICATOR
BORROWER FULL NAME
BORROWER LAST NAME
BORROWER SUFFIX NAME
BORROWER MIDDLE NAME
BORROWER FIRST NAME
PROPERTY ADDRESS ZIPCODE
PROPERTY ADDRESS CITY
PROPERTY ADDRESS LINE 1
PROPERTY ADDRESS LINE 2
PROPERTY ADDRESS STATE
ORIGINATION CHARGES SELLER PAID
ORIGINATION CHARGES PAID BY OTHERS
DISCOUNT POINTS BORROWER PAID AT CLOSING
DISCOUNT POINTS BORROWER PAID BEFORE CLOSING
DISCOUNT POINTS SELLER PAID AT CLOSING
DISCOUNT POINTS SELLER PAID BEFORE CLOSING
DISCOUNT POINTS PAID BY OTHERS
APPRAISAL FEE BORROWER PAID AT CLOSING
APPRAISAL FEE BORROWER PAID BEFORE CLOSING
APPRAISAL FEE SELLER PAID AT CLOSING
APPRAISAL FEE SELLER PAID BEFORE CLOSING
APPRAISAL FEE PAID BY OTHERS
ORIGINATION CHARGES BORROWER PAID
TOTAL LOAN COSTS INTEGRATED DISCLOSURE SECTION TOTAL AMOUNT
PREPAIDS BORROWER PAID
PREPAIDS SELLER PAID
PREPAIDS PAID BY OTHERS
PREPAID INTEREST PREPAID ITEM PAID FROM DATE
PREPAID INTEREST PREPAID ITEM PAID THROUGH DATE
INITIAL ESCROW PAYMENT AT CLOSING BORROWER PAID
INITIAL ESCROW PAYMENT AT CLOSING SELLER PAID
INITIAL ESCROW PAYMENT AT CLOSING PAID BY OTHERS
HOMEOWNERS INSURANCE MONTHLY PAYMENT AMOUNT
HOMEOWNERS INSURANCE ESCROW COLLECTED NUMBER OF MONTHS COUNT
HOMEOWNERS INSURANCE ESCROW ITEM ACTUAL TOTAL AMOUNT
MI ESCROW MONTHLY PAYMENT AMOUNT
MI ESCROW COLLECTED NUMBER OF MONTHS COUNT
PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
PROPERTY TAX ESCROW COLLECTED NUMBER OF MONTHS COUNT
PROPERTY TAX ESCROW ITEM ACTUAL TOTAL AMOUNT
ESCROW AGGREGATE ACCOUNTING ADJUSTMENT AMOUNT
HOMEOWNERS INSURANCE PREPAID ITEM ACTUAL TOTAL AMOUNT
MI PREPAID ITEM BORROWER PAID AT CLOSING
MI PREPAID ITEM BORROWER PAID BEFORE CLOSING
MI PREPAID ITEM PAID BY OTHERS
MI PREPAID ITEM SELLER PAID AT CLOSING
MI PREPAID ITEM SELLER PAID BEFORE CLOSING
TOTAL CLOSING COSTS LENDER CREDITS
TOTAL ESCROW PAYMENT AMOUNT
APR PERCENT
CLOSING AGENT FULL NAME
CLOSING AGENT CITY NAME
FIRST PER CHANGE FLOOR RATE PERCENT
FIRST PER CHANGE MAXIMUM INCREASE RATE PERCENT
FIRST PER CHANGE RATE ADJUSTMENT EFFECTIVE MONTHS COUNT
MARGIN RATE PERCENT
SUBSEQUENT PER CHANGE MAXIMUM INCREASE RATE PERCENT
SUBSEQUENT PER CHANGE RATE ADJUSTMENT EFFECTIVE MONTHS COUNT
CEILING RATE PERCENT
INTEREST ONLY TERM MONTHS COUNT
ESCROW ITEM TYPE OTHER DESCRIPTION
ASSESSMENT TAX ESCROW MONTHLY PAYMENT AMOUNT
CITY BOND TAX ESCROW MONTHLY PAYMENT AMOUNT
CITY PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
CONDOMINIUM ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT
CONDOMINIUM ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT
CONSTRUCTION COMPLETION FUNDS ESCROW MONTHLY PAYMENT AMOUNT
COOPERATIVE ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT
COOPERATIVE ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT
COUNTY BOND TAX ESCROW MONTHLY PAYMENT AMOUNT
COUNTY PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
DISTRICT PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
EARTHQUAKE INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
ENERGY EFFICIENT IMPROVEMENT FUNDS ESCROW MONTHLY PAYMENT AMOUNT
FLOOD INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
HAIL INSURANCE PREMIUM ESCROW MONTHLY PAYMENT AMOUNT
HAZARD INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
HOMEOWNERS ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT
HOMEOWNERS ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT
OTHER ESCROW MONTHLY PAYMENT AMOUNT
PARISH TAX ESCROW MONTHLY PAYMENT AMOUNT
PEST INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
REHABILITATION FUNDS ESCROW MONTHLY PAYMENT AMOUNT
SCHOOL PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
STATE PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
TOWN PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
TOWNSHIP PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
VILLAGE PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT
VOLCANO INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
WINDSTORM INSURANCE ESCROW MONTHLY PAYMENT AMOUNT
FLOOD INSURANCE PREPAID ITEM ACTUAL TOTAL AMOUNT
MI PAYMENT AMOUNT
FIRST PRINCIPAL AND INTEREST PAYMENT CHANGE DATE
SCHEDULED FIRST PAYMENT DATE
INTEREST ONLY MONTHLY PAYMENT AMOUNT

`;
