export const disclosureData = `
Document Type,Data Elements,Group Number,Datapoint Order
Closing Disclosure,PROPERTY ADDRESS ZIPCODE,4,4
Closing Disclosure,BORROWER SIGNATURE PRESENT INDICATOR,3,6
Closing Disclosure,PROPERTY ADDRESS CITY,4,3
Closing Disclosure,PROPERTY ADDRESS LINE 1,4,2
Closing Disclosure,PROPERTY ADDRESS LINE 2,4,1
Closing Disclosure,CASH TO BORROWER AT CLOSING AMOUNT,2,5
Closing Disclosure,CASH FROM BORROWER AT CLOSING AMOUNT,2,4
Closing Disclosure,MI PAYMENT AMOUNT,10,1
Closing Disclosure,DISBURSEMENT DATE,1,3
Closing Disclosure,PREPAYMENT PENALTY INDICATOR,1,14
Closing Disclosure,INITIAL PRINCIPAL AND INTEREST PAYMENT AMOUNT,1,13
Closing Disclosure,INTEREST RATE,1,12
Closing Disclosure,LOAN AMOUNT,1,11
Closing Disclosure,CLOSING DATE,1,2
Closing Disclosure,LOAN AMORTIZATION PERIOD TYPE,1,7
Closing Disclosure,LOAN AMORTIZATION PERIOD COUNT,1,6
Closing Disclosure,DATE ISSUED,1,1
Closing Disclosure,PURCHASE PRICE AMOUNT,1,4
Closing Disclosure,PROPERTY ADDRESS STATE,4,5
Closing Disclosure,PROPERTY TAXES PROJECTED PAYMENT ESCROWED TYPE,2,1
Closing Disclosure,HOMEOWNERS INSURANCE PROJECTED PAYMENT ESCROWED TYPE,2,2
Closing Disclosure,INTEREST ONLY INDICATOR,1,9
Closing Disclosure,BORROWER FULL NAME,3,5
Closing Disclosure,PROJECTED PAYMENT ESTIMATED TAXES INSURANCE ASSESSMENT COMPONENT TYPE,2,3
Closing Disclosure,BORROWER LAST NAME,3,3
Closing Disclosure,BORROWER SUFFIX NAME,3,4
Closing Disclosure,BORROWER MIDDLE NAME,3,2
Closing Disclosure,BORROWER FIRST NAME,3,1
Closing Disclosure,LENDER FULL NAME,1,5
Closing Disclosure,PROJECTED PAYMENT MI PAYMENT AMOUNT,1,16
Closing Disclosure,ORIGINATION CHARGES SELLER PAID,5,2
Closing Disclosure,ORIGINATION CHARGES PAID BY OTHERS,5,3
Closing Disclosure,DISCOUNT POINTS BORROWER PAID AT CLOSING,5,4
Closing Disclosure,DISCOUNT POINTS BORROWER PAID BEFORE CLOSING,5,5
Closing Disclosure,DISCOUNT POINTS SELLER PAID AT CLOSING,5,6
Closing Disclosure,DISCOUNT POINTS SELLER PAID BEFORE CLOSING,5,7
Closing Disclosure,DISCOUNT POINTS PAID BY OTHERS,5,8
Closing Disclosure,APPRAISAL FEE BORROWER PAID AT CLOSING,5,9
Closing Disclosure,APPRAISAL FEE BORROWER PAID BEFORE CLOSING,5,10
Closing Disclosure,APPRAISAL FEE SELLER PAID AT CLOSING,5,11
Closing Disclosure,APPRAISAL FEE SELLER PAID BEFORE CLOSING,5,12
Closing Disclosure,APPRAISAL FEE PAID BY OTHERS,5,13
Closing Disclosure,PREPAIDS BORROWER PAID,6,1
Closing Disclosure,PREPAIDS SELLER PAID,6,2
Closing Disclosure,PREPAIDS PAID BY OTHERS,6,3
Closing Disclosure,PREPAID INTEREST PREPAID ITEM PAID FROM DATE,6,10
Closing Disclosure,PREPAID INTEREST PREPAID ITEM PAID THROUGH DATE,6,11
Closing Disclosure,INITIAL ESCROW PAYMENT AT CLOSING BORROWER PAID,6,12
Closing Disclosure,INITIAL ESCROW PAYMENT AT CLOSING SELLER PAID,6,13
Closing Disclosure,INITIAL ESCROW PAYMENT AT CLOSING PAID BY OTHERS,6,14
Closing Disclosure,HOMEOWNERS INSURANCE MONTHLY PAYMENT AMOUNT,6,15
Closing Disclosure,ESCROW ITEM TYPE OTHER DESCRIPTION,9,1
Closing Disclosure,HOMEOWNERS INSURANCE ESCROW COLLECTED NUMBER OF MONTHS COUNT,6,16
Closing Disclosure,HOMEOWNERS INSURANCE ESCROW ITEM ACTUAL TOTAL AMOUNT,6,17
Closing Disclosure,MI ESCROW MONTHLY PAYMENT AMOUNT,6,18
Closing Disclosure,MI ESCROW COLLECTED NUMBER OF MONTHS COUNT,6,19
Closing Disclosure,PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,6,20
Closing Disclosure,PROPERTY TAX ESCROW COLLECTED NUMBER OF MONTHS COUNT,6,21
Closing Disclosure,PROPERTY TAX ESCROW ITEM ACTUAL TOTAL AMOUNT,6,22
Closing Disclosure,ASSESSMENT TAX ESCROW MONTHLY PAYMENT AMOUNT,9,3
Closing Disclosure,CITY BOND TAX ESCROW MONTHLY PAYMENT AMOUNT,9,3
Closing Disclosure,CITY PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,4
Closing Disclosure,CONDOMINIUM ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT,9,5
Closing Disclosure,CONDOMINIUM ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT,9,6
Closing Disclosure,CONSTRUCTION COMPLETION FUNDS ESCROW MONTHLY PAYMENT AMOUNT,9,7
Closing Disclosure,COOPERATIVE ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT,9,8
Closing Disclosure,COOPERATIVE ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT,9,9
Closing Disclosure,COUNTY BOND TAX ESCROW MONTHLY PAYMENT AMOUNT,9,10
Closing Disclosure,COUNTY PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,11
Closing Disclosure,DISTRICT PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,12
Closing Disclosure,EARTHQUAKE INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,13
Closing Disclosure,ENERGY EFFICIENT IMPROVEMENT FUNDS ESCROW MONTHLY PAYMENT AMOUNT,9,14
Closing Disclosure,FLOOD INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,15
Closing Disclosure,HAIL INSURANCE PREMIUM ESCROW MONTHLY PAYMENT AMOUNT,9,16
Closing Disclosure,HAZARD INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,17
Closing Disclosure,HOMEOWNERS ASSOCIATION DUES ESCROW MONTHLY PAYMENT AMOUNT,9,18
Closing Disclosure,HOMEOWNERS ASSOCIATION SPECIAL ASSESSMENT ESCROW MONTHLY PAYMENT AMOUNT,9,19
Closing Disclosure,OTHER ESCROW MONTHLY PAYMENT AMOUNT,9,20
Closing Disclosure,PARISH TAX ESCROW MONTHLY PAYMENT AMOUNT,9,21
Closing Disclosure,PEST INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,22
Closing Disclosure,REHABILITATION FUNDS ESCROW MONTHLY PAYMENT AMOUNT,9,23
Closing Disclosure,SCHOOL PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,24
Closing Disclosure,STATE PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,25
Closing Disclosure,TOWN PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,26
Closing Disclosure,TOWNSHIP PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,27
Closing Disclosure,VILLAGE PROPERTY TAX ESCROW MONTHLY PAYMENT AMOUNT,9,28
Closing Disclosure,VOLCANO INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,29
Closing Disclosure,WINDSTORM INSURANCE ESCROW MONTHLY PAYMENT AMOUNT,9,30
Closing Disclosure,ESCROW AGGREGATE ACCOUNTING ADJUSTMENT AMOUNT,6,23
Closing Disclosure,FIRST PER CHANGE FLOOR RATE PERCENT,8,3
Closing Disclosure,TOTAL ESCROW PAYMENT AMOUNT,7,1
Closing Disclosure,FIRST PER CHANGE MAXIMUM INCREASE RATE PERCENT,8,4
Closing Disclosure,FIRST PER CHANGE RATE ADJUSTMENT EFFECTIVE MONTHS COUNT,8,6
Closing Disclosure,FIRST PRINCIPAL AND INTEREST PAYMENT CHANGE DATE,10,2
Closing Disclosure,SCHEDULED FIRST PAYMENT DATE,10,3
Closing Disclosure,INTEREST ONLY MONTHLY PAYMENT AMOUNT,10,4
Closing Disclosure,MARGIN RATE PERCENT,8,2
Closing Disclosure,SUBSEQUENT PER CHANGE MAXIMUM INCREASE RATE PERCENT,8,7
Closing Disclosure,SUBSEQUENT PER CHANGE RATE ADJUSTMENT EFFECTIVE MONTHS COUNT,8,5
Closing Disclosure,CEILING RATE PERCENT,8,8
Closing Disclosure,MI INITIAL PREMIUM AMOUNT,1,15
Closing Disclosure,FLOOD INSURANCE PREPAID ITEM ACTUAL TOTAL AMOUNT,9,31
Closing Disclosure,HOMEOWNERS INSURANCE PREPAID ITEM ACTUAL TOTAL AMOUNT,6,4
Closing Disclosure,MORTGAGE TYPE,1,10
Closing Disclosure,LOAN PURPOSE TYPE,1,8
Closing Disclosure,ORIGINATION CHARGES BORROWER PAID,5,1
Closing Disclosure,TOTAL LOAN COSTS INTEGRATED DISCLOSURE SECTION TOTAL AMOUNT,5,14
Closing Disclosure,MI PREPAID ITEM BORROWER PAID AT CLOSING,6,5
Closing Disclosure,MI PREPAID ITEM BORROWER PAID BEFORE CLOSING,6,6
Closing Disclosure,MI PREPAID ITEM PAID BY OTHERS,6,10
Closing Disclosure,MI PREPAID ITEM SELLER PAID AT CLOSING,6,7
Closing Disclosure,MI PREPAID ITEM SELLER PAID BEFORE CLOSING,6,8
Closing Disclosure,TOTAL CLOSING COSTS LENDER CREDITS,6,24
Closing Disclosure,APR PERCENT,7,2
Closing Disclosure,PROPOSED TOTAL MONTHLY HOUSING EXPENSE,1,17
Closing Disclosure,INTEREST ONLY TERM MONTHS COUNT,8,1
Closing Disclosure,CLOSING AGENT FULL NAME,7,4
Closing Disclosure,CLOSING AGENT CITY NAME,7,3
`;
