export const feedbackData = `
Data Elements
PROPERTY ADDRESS ZIPCODE
PROPERTY ADDRESS STATE
PROPERTY ADDRESS CITY
PROPERTY ADDRESS LINE 1
PROPERTY ADDRESS LINE 2
AUTOMATED UNDERWRITING SYSTEM TYPE
OCCUPANCY TYPE
NUMBER OF UNITS
MORTGAGE TYPE
ATTACHMENT TYPE
LOAN PURPOSE TYPE
APPRAISAL AMOUNT
LOAN AMORTIZATION PERIOD TYPE
LOAN AMORTIZATION PERIOD COUNT
DESKTOP UNDERWRITER RECOMMENDATION TYPE
DU VERSION
CASE FILE ID
SUBMISSION NUMBER
SUBMISSION DATE/TIME
SALES PRICE
TOTAL LOAN AMOUNT
LOAN AMOUNT
INTEREST RATE
LTV RATIO PERCENT
TOTAL MONTHLY INCOME AMOUNT
TOTAL DEBT EXPENSE RATIO PERCENT
HOUSING EXPENSE RATIO PERCENT
HOME EQUITY COMBINED LTV RATIO PERCENT
COMBINED LTV RATIO PERCENT
TOTAL LIABILITY MONTHLY PAYMENT AMOUNT
BALLOON INDICATOR
REFINANCE CASH OUT DETERMINATION TYPE
BORROWER RESERVES MONTHLY PAYMENT COUNT
PROPERTY TYPE
INVESTOR FEATURE IDENTIFIER
LIEN PRIORITY TYPE
AGENCY CASE LOAN IDENTIFIER
TOTAL SUBORDINATE FINANCING AMOUNT
TOTAL EXPENSES MONTHLY PAYMENT AMOUNT
PROPOSED TOTAL MONTHLY HOUSING EXPENSE
AUTOMATED UNDERWRITING EXPIRATION DATE
BORROWER SUFFIX NAME
BORROWER LAST NAME
BORROWER MIDDLE NAME
BORROWER OTHER CREDIT SCORE VALUE 1
BORROWER FULL NAME
BORROWER OTHER CREDIT SCORE VALUE 2
BORROWER OTHER CREDIT SCORE VALUE 3
BORROWER FIRST NAME
`;
